### ISSUE TITLE
新旧两个示例站点都打不开了

### ISSUE THREAD

**Issue by teacherpan** [atinc/ngx-tethys#2460]
### Component

other

### Description

新站点：
![image](https://user-images.githubusercontent.com/12424383/210122954-891b3ece-f834-4d12-9894-8638f90b98d6.png)

跳转到登录界面：
![image](https://user-images.githubusercontent.com/12424383/210122986-7c7ee410-541b-4a53-9bb9-25b637109b03.png)

老站点：
![image](https://user-images.githubusercontent.com/12424383/210122944-d9ea1329-0462-48e5-899e-aac07ac916bd.png)
![image](https://user-images.githubusercontent.com/12424383/210122946-df016959-69ab-4ccb-bba5-7eae3c1f205d.png)

**Comment by why520crazy** [comment]
你试试第一个应该好了
